### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by julianakuei** [byn9826/Thousanday-Mobile#1]
Hi, when I run your project, I got this error message.

![image](https://user-images.githubusercontent.com/25919263/27298243-7a0001be-555a-11e7-9234-7aeaee8b022d.png)

BTW, I have updated the latest version of Android Studio.

**Comment by byn9826** [comment]
Hi @julianakuei 
I have uploaded the android folder, please redownload and try to run the project directly.
Build errors always come from third party modules, I'm unable to tell what happens from the screenshot

**Comment by julianakuei** [comment]
thank you for your response :)
but after I ran the project you updated, I still got wrong message.
I don't know which part I got error, before this, I have tried a lot of method learned form other information.

## Here are the message

:app:processDebugResources
D:\Desktop\Thousanday-Mobile\Thousanday\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

D:\Desktop\Thousanday-Mobile\Thousanday\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

D:\Desktop\Thousanday-Mobile\Thousanday\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

D:\Desktop\Thousanday-Mobile\Thousanday\android\app\build\intermediates\res\merged\debug\values-v24\values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.


:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 29.749 secs
Could not install the app on the device, read the error above for details.

**Comment by julianakuei** [comment]
And here is the file

https://github.com/julianakuei/AppTest

**Comment by byn9826** [comment]
@julianakuei 
React Native use ANDROID SDK 23, seems you are using Android SDK 24.
See step 2 here https://facebook.github.io/react-native/docs/getting-started.html
Besides, please re-download the whole project, it should work properly.

**Comment by julianakuei** [comment]
Thanks, it works :)
